name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@2a9625d550eefc3a9b1a43d342ad655f563f8241
        with:
          version: 0.12.0

      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - run:
          cargo install cargo-zigbuild

          rustup target add wasm32-unknown-unknown

          rustup target add x86_64-unknown-linux-gnu
          make CARGO_FLAGS="--target x86_64-unknown-linux-gnu"
          tar cjpf wasi-update_${{ github.ref_name }}_linux-x86_64.tar.bz2 wasi-update

          rustup target add aarch64-unknown-linux-gnu
          make CARGO_FLAGS="--target aarch64-unknown-linux-gnu"
          tar cjpf wasi-update_${{ github.ref_name }}_linux-aarch64.tar.bz2 wasi-update

          rustup target add wasm32-wasi
          make CARGO_FLAGS="--target wasm32-wasi"
          tar cjpf wasi-update_${{ github.ref_name }}_wasm32-wasi.tar.bz2 wasi-update
